
GET http://localhost:3000/api/inmuebles

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": "ssb 70",
    "letra": "A",
    "extension": 5,
    "numero_de_habitacones": 4,
    "alquilado": true,
    "nombre_propietario": "Paco",
    "mail_de_contacto": "ejemplo@ejemplo.es"
}

###
PUT http://localhost:3000/api/inmuebles/646a220882f21b4d65d1b521
Content-Type: application/json

{
    "letra": "Y",
    "nombre_propietario": "Paquito",
    "alquilado": true
}

###
DELETE  http://localhost:3000/api/inmuebles/646a220882f21b4d65d1b521
